apiVersion: v1
#这个是指我k8s有哪些volume
kind: PersistentVolume
metadata:
  name: my-local-pv
  labels:
    role: my-local-pv
spec:
  storageClassName: suibian
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/live"

